spring:
  activiti:
    processDefinitionLocationPrefix: 
    databaseSchemaUpdate: false
    dbIdentityUsed: false
  datasource:
    url: jdbc:mysql://10.5.2.242:3306/prod?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver